/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.UsuariosDAO;
import Javabeans.Tbimc;
import javax.swing.JOptionPane;

/**
 *
 * @author wellt
 */
public class frmImc extends javax.swing.JFrame {

    /**
     * Creates new form frmImc
     */
    public frmImc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtidade = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        txtaltura = new javax.swing.JTextField();
        btncalcular = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cálculo IMC ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Idade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Peso:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Altura:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 220, 30));

        txtidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 80, 30));

        txtpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 80, 30));

        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 80, 30));

        btncalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncalcular.setText("Calcular IMC");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 390, 140, 40));

        btnsalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 90, 40));

        btnlimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 80, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Resultado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        lblresultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblresultado.setText("0");
        getContentPane().add(lblresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
        if (txtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio");
        }
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
    if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo nome é Obrigatorio");
            return;
        }
        
        if(txtidade.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo idade é Obrigatorio");
            return;
        }
        
         if(txtpeso.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo peso é Obrigatorio");
            return;
        }
         if(txtaltura.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo altura é Obrigatorio");
            return;
        }
        
         if(lblresultado.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "O resultado é Obrigatorio");
            return;
         }
        try {
            Tbimc obj = new Tbimc();
            obj.setNome(txtnome.getText());
            obj.setIdade(Integer.parseInt(txtidade.getText()));
            obj.setPeso(Float.parseFloat(txtpeso.getText()));
            obj.setAltura(Float.parseFloat(txtaltura.getText()));
            obj.setResultado(Float.parseFloat(lblresultado.getText()));

            UsuariosDAO dao = new UsuariosDAO();
            dao.cadastrarUsuario(obj);

            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar" + erro);
        }

    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesoActionPerformed
        // TODO add your handling code here:
        if (txtaltura.getText() == null || txtaltura.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio");
        }
    }//GEN-LAST:event_txtpesoActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txtnome.setText("");
        txtidade.setText("");
        txtpeso.setText("");
        txtaltura.setText("");
        lblresultado.setText("0");
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo nome é Obrigatorio");
            return;
        }
        
        if(txtidade.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo idade é Obrigatorio");
            return;
        }
        
         if(txtpeso.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo peso é Obrigatorio");
            return;
        }
         if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo altura é Obrigatorio");
            return;
        }
        
        float altura = Float.valueOf(txtaltura.getText());
        float peso = Float.valueOf(txtpeso.getText());

        float calcular = (peso) / (altura * altura);
        lblresultado.setText(Float.toString(calcular));

        if (calcular < 18) {
            JOptionPane.showMessageDialog(null, "Seu IMC = " + calcular + "Voce esta abaixo do peso");
        } else if (calcular >= 18 && calcular <= 25) {
            JOptionPane.showMessageDialog(null, "Seu IMC = " + calcular + "Parabéns voce está no peso ideal!!!");

        } else if (calcular >= 26 && calcular <= 35) {
            JOptionPane.showMessageDialog(null, "Seu IMC = " + calcular + "Obesidade Grau 1");

        } else if (calcular >= 36 && calcular <= 39) {
            JOptionPane.showMessageDialog(null, "Seu IMC = " + calcular + "Obesidade Grau 2 (severa)");

        } else if (calcular >= 40) {
            JOptionPane.showMessageDialog(null, "Seu IMC = " + calcular + "Obesidade Grau 3 (mórbida");

        }
    }//GEN-LAST:event_btncalcularActionPerformed

    private void txtidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidadeActionPerformed
        // TODO add your handling code here:

        if (txtaltura.getText() == null || txtaltura.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio");
        }
    }//GEN-LAST:event_txtidadeActionPerformed

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:

        if (txtaltura.getText() == null || txtaltura.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio");

        }

    }//GEN-LAST:event_txtalturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmImc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmImc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtidade;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables
}
